version: "3"

services:
  app:
    build:
      context: app
    ports:
      - "8010"
  nginx:
    image: nginx:latest
    volumes:
      - ./app/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    ports:
      - "80:80"
